Implemented Article Page routing and Article Layout
Mahmoudgalalz/salamy-mirror pull request #1
Opened 2023-12-14 13:52 UTC by AmrTamer23

2023-12-16 11:13 UTC, Mahmoudgalalz commented on src/app/articleGroup/[groupSlug]/article/[articleSlug]/page.tsx
> +            <h2 className="3xl:text-xl">بواسطة مصطفي جمال مراجعة محمد سلطان</h2>
This is a bad for SEO

should be anything else, don't ever use h<> for anything, and leveling is so important

2023-12-16 11:17 UTC, Mahmoudgalalz requested changes
as I said, there's a lot of SEO things needs to be optimized

also we need to add meta,data here
specially 

so in the Layout make sure to include OG image same as the image in the article, title and description

2023-12-16 11:17 UTC, Mahmoudgalalz commented on src/app/articleGroup/[groupSlug]/article/[articleSlug]/page.tsx
> +              <h6 className="text-sm 3xl:text-lg">
The name of the article would be h6 ?! is that the title?

2023-12-16 11:17 UTC, Mahmoudgalalz commented on src/app/components/Article/ArticleFooter.tsx
> +            <h4 className="text-black text-xl 3xl:text-2xl"> روابط مفيدة</h4>
Cannot be h4 or any h

2023-12-16 14:07 UTC, AmrTamer23 commented on src/app/articleGroup/[groupSlug]/article/[articleSlug]/page.tsx
> +              <h6 className="text-sm 3xl:text-lg">
This is the main category's name, but I will change the h6 as it's bad for leveling

2023-12-17 13:25 UTC, Mahmoudgalalz approved these changes

2023-12-17 13:26 UTC, merged